spring.config.import=optional:file:${user.dir}/.env[.properties],optional:file:./.env[.properties],optional:file:.env[.properties]
server.port=${SERVER_PORT:8080}
spring.application.name=rental_room_service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false


spring.flyway.enabled=${FLYWAY_ENABLED:false}

oauth2.client.internal-id=${OAUTH2_CLIENT_INTERNAL_ID}
oauth2.client.id=${OAUTH2_CLIENT_ID:rental-client}
oauth2.client.secret=${OAUTH2_CLIENT_SECRET}
oauth2.client.redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:3000/callback}
authorization-server.issuer=${AUTHORIZATION_SERVER_ISSUER:http://localhost:8080}

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}

springdoc.swagger-ui.path=/swagger-ui.html
